environment:
  nodejs_version: "8"
  GOPATH: c:\gopath

version: 1.0.{build}
init:
- ps: Install-Product node $env:nodejs_version
- ps: sleep 10
- ps: npm install npm@latest -g
- ps: node --version
- ps: npm --version

build_script:
- ps: |
    go get -d github.com/getgauge/gauge
    cd $env:GOPATH\src\github.com\getgauge\gauge
    git checkout request_timeout
    go get github.com/getgauge/gauge
    cd $env:APPVEYOR_BUILD_FOLDER
    $env:Path = "c:\Program Files\Gauge\bin;" + [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") + ";" +  "c:\gopath\bin"
    Write-Host "PATH : $($env:PATH)"
    gauge version
    gauge install
    gauge version
cache:
- packages
- '%APPDATA%\gauge\plugins'
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/68b514dcb2c08a6a5809
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
test_script:
- ps: npm install
- ps: gauge run specs
artifacts:
- path: ./reports/html-reportreport
  name: gauge-reports
- path: ./failure_reports/html-report
  name: gauge-reports-failure
on_finish:
- ps: >-
    # upload results to AppVeyor
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\reports\xml-report\result.xml))
